//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniCAS.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniCAS.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I expect a {0}..
        /// </summary>
        internal static string ExpectTokenException {
            get {
                return ResourceManager.GetString("ExpectTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For a positive integer n returns the factorization of n.
        /// </summary>
        internal static string ifactorsDef {
            get {
                return ResourceManager.GetString("ifactorsDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perform divisions between their prime divisors until we get a one in the quotient..
        /// </summary>
        internal static string IFactorsDetail1 {
            get {
                return ResourceManager.GetString("IFactorsDetail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expected {0} max params.
        /// </summary>
        internal static string MaxNumParamsException {
            get {
                return ResourceManager.GetString("MaxNumParamsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expected {0} min parametros.
        /// </summary>
        internal static string MinNumParamsException {
            get {
                return ResourceManager.GetString("MinNumParamsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I didn&apos;t expect a {0}..
        /// </summary>
        internal static string NoExpectTokenException {
            get {
                return ResourceManager.GetString("NoExpectTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; is not integer..
        /// </summary>
        internal static string NoExpressionInteger {
            get {
                return ResourceManager.GetString("NoExpressionInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; not is integer.
        /// </summary>
        internal static string NoIntegerException {
            get {
                return ResourceManager.GetString("NoIntegerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I don&apos;t recognize &apos;{0}&apos;.
        /// </summary>
        internal static string NoRecognizeStError {
            get {
                return ResourceManager.GetString("NoRecognizeStError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expected {0} params.
        /// </summary>
        internal static string NumParamsException {
            get {
                return ResourceManager.GetString("NumParamsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} hour.
        /// </summary>
        internal static string TimespanHour {
            get {
                return ResourceManager.GetString("TimespanHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} hours.
        /// </summary>
        internal static string TimespanHours {
            get {
                return ResourceManager.GetString("TimespanHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ms.
        /// </summary>
        internal static string TimespanMiliSeconds {
            get {
                return ResourceManager.GetString("TimespanMiliSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} minute.
        /// </summary>
        internal static string TimespanMinute {
            get {
                return ResourceManager.GetString("TimespanMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} minutes.
        /// </summary>
        internal static string TimespanMinutes {
            get {
                return ResourceManager.GetString("TimespanMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} second.
        /// </summary>
        internal static string TimespanSecond {
            get {
                return ResourceManager.GetString("TimespanSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} seconds.
        /// </summary>
        internal static string TimespanSeconds {
            get {
                return ResourceManager.GetString("TimespanSeconds", resourceCulture);
            }
        }
    }
}
